[tools]
delta = "latest"
fzf = "latest"
"github:RivoLink/leaf" = "latest"
herdr = "latest"
lazygit = "latest"
mysql = "latest"
neovim = "latest"
node = "lts"
python = "latest"
terraform = "latest"
worktrunk = "latest"

[settings]
experimental = true
